### ISSUE TITLE
Fix style cho description trên Hero section (Trang chủ)

### ISSUE THREAD

**Issue by hoangquan123** [hoangquan123/duocsoiduong#1]
### Mô tả
Fix style cho dòng chữ 
`Đuốc Soi Đường là một CLB thuộc trường THPT Chuyên Lý Tự Trọng - Cần Thơ. Được thành lập vào năm 2019 bởi một nhóm học sinh của trường có niềm đam mê khám phá tri thức.`
Kích thước to hơn bình thường + màu sắc không phù hợp.

### Cách phát hiện lỗi
- Truy cập https://duocsoiduong.xyz/
- Quan sát phần Hero

### Thao tác để tạo lỗi
Không cần thao tác thêm

### Hướng giải quyết
- Màu đúng là rgb(87, 82, 80).
- Font size 18px

### Cấu hình hệ thống
Trình duyệt Chrome

**Comment by kirito99152** [comment]
xong
