### ISSUE TITLE
Thanh menu trên header không hiển thị sau khi truy cập

### ISSUE THREAD

**Issue by hoangquan123** [hoangquan123/duocsoiduong#2]
### Mô tả
Phần menu (Home, News Feed, ...) trên header không hiển thị sau vài lần truy cập

### Cách phát hiện lỗi
- Truy cập https://duocsoiduong.xyz/

### Thao tác để tạo lỗi
- Reload lại trang

### Hướng giải quyết
n/a

### Cấu hình hệ thống
Trình duyệt Chrome

**Comment by kirito99152** [comment]
xong
