### ISSUE TITLE
Footer không có margin, padding, font khớp với bố cục tổng thể

### ISSUE THREAD

**Issue by hoangquan123** [hoangquan123/duocsoiduong#3]
### Mô tả
Footer không có margin, padding, font khớp với bố cục tổng thể. Cần chỉnh sửa lại

### Cách phát hiện lỗi
- Truy cập https://duocsoiduong.xyz/

### Thao tác để tạo lỗi
- Scroll đến phần Footer

### Hướng giải quyết
n/a

### Cấu hình hệ thống
Trình duyệt Chrome

**Comment by hoangquan123** [comment]
Và kích thước logo ở footer khá to, không cân đối so với header.

**Comment by hoangquan123** [comment]
Icon ở footer cũng bị lỗi do dùng sai class của Font Awesome bản mới nhất.

**Comment by kirito99152** [comment]
xong
