### ISSUE TITLE
Hình ảnh bị bóp méo khi kích thước màn hình nhỏ (tablet)

### ISSUE THREAD

**Issue by hoangquan123** [hoangquan123/duocsoiduong#4]
### Mô tả
Hình ảnh chiếc cúp bị bóp méo trên các kích cỡ màn hình như tablet.
![image](https://user-images.githubusercontent.com/22959129/184521822-de54412f-58dd-4326-9baa-e863c96253f7.png)

### Cách phát hiện lỗi
- Truy cập https://duocsoiduong.xyz/ trên thiết bị có màn hình cỡ tablet (hoặc sử dụng Chrome Dev tools)

### Thao tác để tạo lỗi
- Quan sát phần Hero trên Trang chủ

### Hướng giải quyết
n/a

### Cấu hình hệ thống
Trình duyệt Chrome

**Comment by kirito99152** [comment]
xong
